DROP TABLE IF EXISTS CUSTOMER;

CREATE TABLE CUSTOMER
(
    ID           VARCHAR(40)  NOT NULL,
    NAME         VARCHAR(100) NOT NULL,
    EMAIL        VARCHAR(100) NOT NULL,
    CREATED_TIME TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);
